language: objective-c
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
  - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/simctl create five com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-8-1
gemfile:
  - Gemfile
cache:
  directories:
  - vendor/bundle
  - vendor/Pods
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake clean
  - bundle exec rake pod:install > /dev/null
script:
  - bundle exec rake spec output=test_unit
  - bundle exec rake spec output=test_unit device_name=five
