language: objective-c
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
  - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/simctl create five com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-8-1
gemfile:
  - Gemfile
script:
  - bundle install
  - bundle exec rake clean
  - bundle exec rake pod:install > /dev/null
  - bundle exec rake spec
  - bundle exec rake spec device_name=five
